" Use Vim settings, rather then Vi settings (much better!).
" This must be first, because it changes other options as a side effect.
set nocompatible

" Automatically add any extenstions found in .vim/bundle
call pathogen#infect()

" allow backspacing over everything in insert mode
set backspace=indent,eol,start

if ! has("gui_running")
	set t_Co=256
endif

" In many terminal emulators the mouse works just fine, thus enable it.
if has('mouse')
  set mouse=a
endif

set background=dark
colors peaksea

" Load indentation rules and plugins according to the detected filetype.
if has("autocmd")
  filetype plugin indent on
endif

set number        " Show line numbers
set showcmd       " Show (partial) command in status line.
set showmatch     " Show matching brackets.
set ignorecase    " Do case insensitive matching
set smartcase     " Do smart case matching
set incsearch     " Incremental search
set autowrite     " Automatically save before commands like :next and :make
set ruler         " always show current position

" leader is comma
let mapleader=","

" turn off search highlight with ,-<space>
nnoremap <leader><space> :nohlsearch<CR>

" Enable syntax highlighting
syntax on

" Create swap and backup files outside of local folder if possible
set directory^=$HOME/.vimtmp//
set backupdir^=$HOME/.vimtmp//
