set number

" Use Vim settings, rather then Vi settings (much better!).
" This must be first, because it changes other options as a side effect.
set nocompatible

" Automatically add any extenstions found in .vim/bundle
call pathogen#infect()

" allow backspacing over everything in insert mode
set backspace=indent,eol,start

if ! has("gui_running")
	set t_Co=256
endif

" In many terminal emulators the mouse works just fine, thus enable it.
if has('mouse')
  set mouse=a
endif

set background=dark
colors peaksea
