# ~/.bashrc: executed by bash(1) for non-login shells.

# If not running interactively, don't do anything
[ -z "$PS1" ] && return

# don't put duplicate lines in the history. See bash(1) for more options
# don't overwrite GNU Midnight Commander's setting of `ignorespace'.
HISTCONTROL=$HISTCONTROL${HISTCONTROL+:}ignoredups

# append to the history file, don't overwrite it
shopt -s histappend

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# fancy prompt (w/ git info)
[ ! -f ~/.bash_prompt ] || . ~/.bash_prompt

# enable programmable completion features
if [ -f ~/bash_completion ] && ! shopt -oq posix; then
    . ~/bash_completion
fi

# Where should this go?
export MAVEN_OPTS="-Xmx512m -XX:MaxPermSize=256m"

# Autosave VIM buffers before executing a terminal command
[ ! -f ~/.vim/bundle/tmux-config/tmux-autowrite/autowrite-vim.sh ] || . ~/.vim/bundle/tmux-config/tmux-autowrite/autowrite-vim.sh

[ ! -f ~/.aliases ] || . ~/.aliases

[ ! -f ~/.git_aliases ] || . ~/.git_aliases

[ ! -f ~/.tmux_aliases ] || . ~/.tmux_aliases

[ ! -f ~/.local_aliases ] || . ~/.local_aliases

[ ! -f ~/.project_aliases ] || . ~/.project_aliases

